### ISSUE TITLE
US 6-2: Signup/Signout Dynamic Text

### ISSUE THREAD

**Issue by chrislhughes01** [CSE112-team1/CSE112-team1#32]

**Comment by ChiaHan1** [comment]
# Dynamic Change Signin/Signout Button

[a3fe0c3](https://github.com/CSE112-team1/CSE112-team1/commit/a3fe0c304e0491b78e855e6b8cdabe4659775479): Since the page will reload every time the user logins or logouts, I checked the sign in status when the page is loaded and modify the text content of the button accordingly.
